CREATE TABLE movies (
    imdbID TEXT,
	Type TEXT,
	Title TEXT,
	Year TEXT,
	Rated TEXT,
	Released TEXT,
	Runtime TEXT,
	Genre TEXT,
	Director TEXT,
	Writer TEXT,
	Actors TEXT,
	Plot TEXT,
	Language TEXT,
	Country TEXT,
	Awards TEXT,
	Poster TEXT,
	Metascore TEXT,
	imdbRating TEXT,
	imdbVotes TEXT,
	DVD TEXT,
	Production TEXT,
	Website TEXT,
	Assistido TEXT,
	Adicionado TEXT,
	dataInsert datetime DEFAULT CURRENT_TIMESTAMP
);